spring.application.name=nhom1
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=nhom1;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=749516
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# server.servlet.encoding.charset=UTF-8
# server.servlet.encoding.enabled=true
# server.servlet.encoding.force=true

# spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
# spring.jpa.properties.hibernate.connection.useUnicode=true